'use client'
import { Typography } from '@mui/material'
import Head from 'next/head'
import { useSettings } from 'src/hooks/useSettings'

export default function Home() {
  // const fetchApiUser = async () => {
  //   await axios.get('http://localhost:3001/api/users?limit=10&page=1&order=created%20asc').then(res => {
  //     console.log(res)
  //   })
  // }
  // useEffect(() => {
  //   fetchApiUser()
  // }, [])
  // const theme = useTheme()
  // console.log('theme: ', theme)
  const { settings } = useSettings()
  console.log(settings)

  return (
    <>
      <Head>
        <title>Manh Tran duc</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Typography>Hello world!</Typography>
    </>
  )
}
